### ISSUE TITLE
About news headlines entity  embedding

### ISSUE THREAD

**Issue by 1607722534** [taoqi98/CAUM#2]
In line 70 of the Utils.py，"title_entity_emb.pkl" is the header entity embedded in the file? There is no process for processing and saving files in the code, and the entity words are embedded in the same way as the words in the title? Or is it a separate entity embedded? It seems that the code for that FUM is the same.

**Comment by taoqi98** [comment]
Hi, thank you for your attention to our work. This file contains entities in news titles and their TransE embeddings provided in the original dataset. This file dumps a dictionary variable, where the key is entity ID and the value is its TransE embedding. I will release this file soon.

**Comment by taoqi98** [comment]
You can download the file via https://drive.google.com/file/d/1FxaiEHIDhXmSJq9gMlX16vi-LqZEaEj0/view?usp=sharing
